import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";

const inter = Inter({ subsets: ["latin"] });
import NavBar from "../components/navbar/NavBar";
import Footer from "../components/footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <NavBar />
          {children}
          <Footer />
        </body>
      </Providers>
    </html>
  );
}
